ADD_DEFINITIONS(
	-DWEBP_DLL
	-DBUILDING_WEBP_DLL
)

ADD_LIBRARY(${LIBWEBP_LIBRARY_NAME} SHARED ${LIBWEBP_HEADERS} ${LIBWEBP_SOURCES})
SET_TARGET_PROPERTIES(${LIBWEBP_LIBRARY_NAME} PROPERTIES FOLDER "webp")
