# DO NOT DELETE

pai_com_server.o: /usr/include/fcntl.h /usr/include/features.h
pai_com_server.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
pai_com_server.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
pai_com_server.o: /usr/include/bits/fcntl.h /usr/include/sys/types.h
pai_com_server.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
pai_com_server.o: /usr/include/time.h /usr/include/endian.h
pai_com_server.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
pai_com_server.o: /usr/include/sys/select.h /usr/include/bits/select.h
pai_com_server.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
pai_com_server.o: /usr/include/sys/sysmacros.h
pai_com_server.o: /usr/include/bits/pthreadtypes.h /usr/include/sys/ioctl.h
pai_com_server.o: /usr/include/bits/ioctls.h /usr/include/asm/ioctls.h
pai_com_server.o: /usr/include/asm-generic/ioctls.h
pai_com_server.o: /usr/include/linux/ioctl.h /usr/include/asm/ioctl.h
pai_com_server.o: /usr/include/asm-generic/ioctl.h
pai_com_server.o: /usr/include/bits/ioctl-types.h
pai_com_server.o: /usr/include/sys/ttydefaults.h /usr/include/linux/types.h
pai_com_server.o: /usr/include/asm/types.h /usr/include/asm-generic/types.h
pai_com_server.o: /usr/include/asm-generic/int-ll64.h
pai_com_server.o: /usr/include/asm/bitsperlong.h
pai_com_server.o: /usr/include/asm-generic/bitsperlong.h
pai_com_server.o: /usr/include/linux/posix_types.h
pai_com_server.o: /usr/include/linux/stddef.h /usr/include/asm/posix_types.h
pai_com_server.o: /usr/include/asm/posix_types_32.h /usr/include/stdio.h
pai_com_server.o: /usr/include/libio.h /usr/include/_G_config.h
pai_com_server.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
pai_com_server.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
pai_com_server.o: /usr/include/alloca.h /usr/include/string.h
pai_com_server.o: /usr/include/xlocale.h /usr/include/pthread.h
pai_com_server.o: /usr/include/sched.h /usr/include/bits/sched.h
pai_com_server.o: /usr/include/signal.h /usr/include/bits/setjmp.h
pai_com_server.o: /usr/include/sys/un.h /usr/include/bits/sockaddr.h
pai_com_server.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
pai_com_server.o: /usr/include/bits/uio.h /usr/include/bits/socket.h
pai_com_server.o: /usr/include/asm/socket.h /usr/include/asm-generic/socket.h
pai_com_server.o: /usr/include/asm/sockios.h
pai_com_server.o: /usr/include/asm-generic/sockios.h /usr/include/errno.h
pai_com_server.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pai_com_server.o: /usr/include/asm/errno.h /usr/include/asm-generic/errno.h
pai_com_server.o: /usr/include/asm-generic/errno-base.h /usr/include/unistd.h
pai_com_server.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
pai_com_server.o: /usr/include/getopt.h /usr/include/sys/epoll.h
pai_com_server.o: /usr/include/stdint.h /usr/include/bits/wchar.h
pai_com_server.o: /usr/include/pulse/pulseaudio.h
pai_com_server.o: /usr/include/pulse/mainloop-api.h /usr/include/sys/time.h
pai_com_server.o: /usr/include/pulse/cdecl.h /usr/include/pulse/sample.h
pai_com_server.o: /usr/include/inttypes.h /usr/include/sys/param.h
pai_com_server.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
pai_com_server.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
pai_com_server.o: /usr/include/bits/posix2_lim.h /usr/include/linux/param.h
pai_com_server.o: /usr/include/asm/param.h /usr/include/asm-generic/param.h
pai_com_server.o: /usr/include/math.h /usr/include/bits/huge_val.h
pai_com_server.o: /usr/include/bits/huge_valf.h /usr/include/bits/huge_vall.h
pai_com_server.o: /usr/include/bits/inf.h /usr/include/bits/nan.h
pai_com_server.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
pai_com_server.o: /usr/include/pulse/gccmacro.h /usr/include/pulse/version.h
pai_com_server.o: /usr/include/pulse/def.h /usr/include/pulse/context.h
pai_com_server.o: /usr/include/pulse/operation.h
pai_com_server.o: /usr/include/pulse/proplist.h /usr/include/pulse/stream.h
pai_com_server.o: /usr/include/pulse/channelmap.h /usr/include/pulse/volume.h
pai_com_server.o: /usr/include/pulse/introspect.h
pai_com_server.o: /usr/include/pulse/subscribe.h /usr/include/pulse/scache.h
pai_com_server.o: /usr/include/pulse/error.h /usr/include/pulse/xmalloc.h
pai_com_server.o: /usr/include/assert.h /usr/include/pulse/utf8.h
pai_com_server.o: /usr/include/pulse/thread-mainloop.h
pai_com_server.o: /usr/include/pulse/mainloop.h
pai_com_server.o: /usr/include/pulse/mainloop-signal.h
pai_com_server.o: /usr/include/pulse/util.h /usr/include/pulse/timeval.h
pai_com_server.o: /usr/include/pulse/rtclock.h /usr/include/pulsecore/macro.h
pai_com_server.o: /usr/include/pulsecore/log.h /usr/include/pulse/i18n.h
pai_com_server.o: /usr/include/pulsecore/core-util.h
