#ifndef IAP2_LOAD_TEST_COPY_SUBPARAMETER_H
#define IAP2_LOAD_TEST_COPY_SUBPARAMETER_H

#include "iap2_load_test.h"

S32 iap2CopyiAP2BluetoothComponentProfiles(iAP2BluetoothComponentProfiles** pdest_iAP2BluetoothComponentProfiles, iAP2BluetoothComponentProfiles* psrc_iAP2BluetoothComponentProfiles);
S32 iap2CopyiAP2BluetoothComponentStatus(iAP2BluetoothComponentStatus** pdest_iAP2BluetoothComponentStatus, iAP2BluetoothComponentStatus* psrc_iAP2BluetoothComponentStatus);
S32 iap2CopyiAP2BluetoothTransportComponent(iAP2BluetoothTransportComponent** pdest_iAP2BluetoothTransportComponent, iAP2BluetoothTransportComponent* psrc_iAP2BluetoothTransportComponent);
S32 iap2CopyiAP2ExternalAccessoryProtocol(iAP2ExternalAccessoryProtocol** pdest_iAP2ExternalAccessoryProtocol, iAP2ExternalAccessoryProtocol* psrc_iAP2ExternalAccessoryProtocol);
S32 iap2CopyiAP2iAP2HIDComponent(iAP2iAP2HIDComponent** pdest_iAP2iAP2HIDComponent, iAP2iAP2HIDComponent* psrc_iAP2iAP2HIDComponent);
S32 iap2CopyiAP2LocationInformationComponent(iAP2LocationInformationComponent** pdest_iAP2LocationInformationComponent, iAP2LocationInformationComponent* psrc_iAP2LocationInformationComponent);
S32 iap2CopyiAP2MediaItem(iAP2MediaItem** pdest_iAP2MediaItem, iAP2MediaItem* psrc_iAP2MediaItem);
S32 iap2CopyiAP2MediaItemAttributes(iAP2MediaItemAttributes** pdest_iAP2MediaItemAttributes, iAP2MediaItemAttributes* psrc_iAP2MediaItemAttributes);
S32 iap2CopyiAP2MediaItemProperties(iAP2MediaItemProperties** pdest_iAP2MediaItemProperties, iAP2MediaItemProperties* psrc_iAP2MediaItemProperties);
S32 iap2CopyiAP2MediaLibraryInformationSubParameter(iAP2MediaLibraryInformationSubParameter** pdest_iAP2MediaLibraryInformationSubParameter, iAP2MediaLibraryInformationSubParameter* psrc_iAP2MediaLibraryInformationSubParameter);
S32 iap2CopyiAP2MediaPlayList(iAP2MediaPlayList** pdest_iAP2MediaPlayList, iAP2MediaPlayList* psrc_iAP2MediaPlayList);
S32 iap2CopyiAP2MediaPlaylistProperties(iAP2MediaPlaylistProperties** pdest_iAP2MediaPlaylistProperties, iAP2MediaPlaylistProperties* psrc_iAP2MediaPlaylistProperties);
S32 iap2CopyiAP2PlaybackAttributes(iAP2PlaybackAttributes** pdest_iAP2PlaybackAttributes, iAP2PlaybackAttributes* psrc_iAP2PlaybackAttributes);
S32 iap2CopyiAP2SerialTransportComponent(iAP2SerialTransportComponent** pdest_iAP2SerialTransportComponent, iAP2SerialTransportComponent* psrc_iAP2SerialTransportComponent);
S32 iap2CopyiAP2StartNowPlayingPlaybackAttributes(iAP2StartNowPlayingPlaybackAttributes** pdest_iAP2StartNowPlayingPlaybackAttributes, iAP2StartNowPlayingPlaybackAttributes* psrc_iAP2StartNowPlayingPlaybackAttributes);
S32 iap2CopyiAP2USBDeviceTransportComponent(iAP2USBDeviceTransportComponent** pdest_iAP2USBDeviceTransportComponent, iAP2USBDeviceTransportComponent* psrc_iAP2USBDeviceTransportComponent);
S32 iap2CopyiAP2USBHostHIDComponent(iAP2USBHostHIDComponent** pdest_iAP2USBHostHIDComponent, iAP2USBHostHIDComponent* psrc_iAP2USBHostHIDComponent);
S32 iap2CopyiAP2USBHostTransportComponent(iAP2USBHostTransportComponent** pdest_iAP2USBHostTransportComponent, iAP2USBHostTransportComponent* psrc_iAP2USBHostTransportComponent);
S32 iap2CopyiAP2VehicleInformationComponent(iAP2VehicleInformationComponent** pdest_iAP2VehicleInformationComponent, iAP2VehicleInformationComponent* psrc_iAP2VehicleInformationComponent);
S32 iap2CopyiAP2VehicleStatusComponent(iAP2VehicleStatusComponent** pdest_iAP2VehicleStatusComponent, iAP2VehicleStatusComponent* psrc_iAP2VehicleStatusComponent);

#endif /* IAP2_LOAD_TEST_COPY_SUBPARAMETER_H */
