#ifndef IAP2_LOAD_TEST_COPY_PARAMETER_H
#define IAP2_LOAD_TEST_COPY_PARAMETER_H

#include "iap2_load_test.h"

S32 iap2CopyiAP2RequestAuthenticationChallengeResponseParameter(iAP2RequestAuthenticationChallengeResponseParameter** pdest_iAP2RequestAuthenticationChallengeResponseParameter, iAP2RequestAuthenticationChallengeResponseParameter* psrc_iAP2RequestAuthenticationChallengeResponseParameter);
S32 iap2CopyiAP2IdentificationRejectedParameter(iAP2IdentificationRejectedParameter** pdest_iAP2IdentificationRejectedParameter, iAP2IdentificationRejectedParameter* psrc_iAP2IdentificationRejectedParameter);
S32 iap2CopyiAP2AssistiveTouchInformationParameter(iAP2AssistiveTouchInformationParameter** pdest_iAP2AssistiveTouchInformationParameter, iAP2AssistiveTouchInformationParameter* psrc_iAP2AssistiveTouchInformationParameter);
S32 iap2CopyiAP2BluetoothConnectionUpdateParameter(iAP2BluetoothConnectionUpdateParameter** pdest_iAP2BluetoothConnectionUpdateParameter, iAP2BluetoothConnectionUpdateParameter* psrc_iAP2BluetoothConnectionUpdateParameter);
S32 iap2CopyiAP2DeviceAuthenticationCertificateParameter(iAP2DeviceAuthenticationCertificateParameter** pdest_iAP2DeviceAuthenticationCertificateParameter, iAP2DeviceAuthenticationCertificateParameter* psrc_iAP2DeviceAuthenticationCertificateParameter);
S32 iap2CopyiAP2DeviceAuthenticationResponseParameter(iAP2DeviceAuthenticationResponseParameter** pdest_iAP2DeviceAuthenticationResponseParameter, iAP2DeviceAuthenticationResponseParameter* psrc_iAP2DeviceAuthenticationResponseParameter);
S32 iap2CopyiAP2DeviceInformationUpdateParameter(iAP2DeviceInformationUpdateParameter** pdest_iAP2DeviceInformationUpdateParameter, iAP2DeviceInformationUpdateParameter* psrc_iAP2DeviceInformationUpdateParameter);
S32 iap2CopyiAP2DeviceLanguageUpdateParameter(iAP2DeviceLanguageUpdateParameter** pdest_iAP2DeviceLanguageUpdateParameter, iAP2DeviceLanguageUpdateParameter* psrc_iAP2DeviceLanguageUpdateParameter);
S32 iap2CopyiAP2StartExternalAccessoryProtocolSessionParameter(iAP2StartExternalAccessoryProtocolSessionParameter** pdest_iAP2StartExternalAccessoryProtocolSessionParameter, iAP2StartExternalAccessoryProtocolSessionParameter* psrc_iAP2StartExternalAccessoryProtocolSessionParameter);
S32 iap2CopyiAP2StopExternalAccessoryProtocolSessionParameter(iAP2StopExternalAccessoryProtocolSessionParameter** pdest_iAP2StopExternalAccessoryProtocolSessionParameter, iAP2StopExternalAccessoryProtocolSessionParameter* psrc_iAP2StopExternalAccessoryProtocolSessionParameter);
S32 iap2CopyiAP2DeviceHIDReportParameter(iAP2DeviceHIDReportParameter** pdest_iAP2DeviceHIDReportParameter, iAP2DeviceHIDReportParameter* psrc_iAP2DeviceHIDReportParameter);
S32 iap2CopyiAP2StartLocationInformationParameter(iAP2StartLocationInformationParameter** pdest_iAP2StartLocationInformationParameter, iAP2StartLocationInformationParameter* psrc_iAP2StartLocationInformationParameter);
S32 iap2CopyiAP2MediaLibraryInformationParameter(iAP2MediaLibraryInformationParameter** pdest_iAP2MediaLibraryInformationParameter, iAP2MediaLibraryInformationParameter* psrc_iAP2MediaLibraryInformationParameter);
S32 iap2CopyiAP2MediaLibraryUpdateParameter(iAP2MediaLibraryUpdateParameter** pdest_iAP2MediaLibraryUpdateParameter, iAP2MediaLibraryUpdateParameter* psrc_iAP2MediaLibraryUpdateParameter);
S32 iap2CopyiAP2NowPlayingUpdateParameter(iAP2NowPlayingUpdateParameter** pdest_iAP2NowPlayingUpdateParameter, iAP2NowPlayingUpdateParameter* psrc_iAP2NowPlayingUpdateParameter);
S32 iap2CopyiAP2PowerUpdateParameter(iAP2PowerUpdateParameter** pdest_iAP2PowerUpdateParameter, iAP2PowerUpdateParameter* psrc_iAP2PowerUpdateParameter);
S32 iap2CopyiAP2TelephonyCallStateInformationParameter(iAP2TelephonyCallStateInformationParameter** pdest_iAP2TelephonyCallStateInformationParameter, iAP2TelephonyCallStateInformationParameter* psrc_iAP2TelephonyCallStateInformationParameter);
S32 iap2CopyiAP2TelephonyUpdateParameter(iAP2TelephonyUpdateParameter** pdest_iAP2TelephonyUpdateParameter, iAP2TelephonyUpdateParameter* psrc_iAP2TelephonyUpdateParameter);
S32 iap2CopyiAP2USBDeviceModeAudioInformationParameter(iAP2USBDeviceModeAudioInformationParameter** pdest_iAP2USBDeviceModeAudioInformationParameter, iAP2USBDeviceModeAudioInformationParameter* psrc_iAP2USBDeviceModeAudioInformationParameter);
S32 iap2CopyiAP2StartVehicleStatusUpdatesParameter(iAP2StartVehicleStatusUpdatesParameter** pdest_iAP2StartVehicleStatusUpdatesParameter, iAP2StartVehicleStatusUpdatesParameter* psrc_iAP2StartVehicleStatusUpdatesParameter);
S32 iap2CopyiAP2VoiceOverCursorUpdateParameter(iAP2VoiceOverCursorUpdateParameter** pdest_iAP2VoiceOverCursorUpdateParameter, iAP2VoiceOverCursorUpdateParameter* psrc_iAP2VoiceOverCursorUpdateParameter);
S32 iap2CopyiAP2VoiceOverUpdateParameter(iAP2VoiceOverUpdateParameter** pdest_iAP2VoiceOverUpdateParameter, iAP2VoiceOverUpdateParameter* psrc_iAP2VoiceOverUpdateParameter);
S32 iap2CopyiAP2WiFiInformationParameter(iAP2WiFiInformationParameter** pdest_iAP2WiFiInformationParameter, iAP2WiFiInformationParameter* psrc_iAP2WiFiInformationParameter);

#endif /* IAP2_LOAD_TEST_COPY_PARAMETER_H */
